repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-ast
    -   id: check-json
    -   id: check-toml
    -   id: detect-private-key
    -   id: name-tests-test
        args: ["--django"]
        name: "Tests should match test_*.py"

- repo: https://github.com/PyCQA/flake8
  rev: 7.3.0
  hooks:
      - id: flake8
        language_version: python3
        args: ["--max-line-length=100"]

-   repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
      - id: black
        language_version: python3
        args: ["--line-length=100"]


- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.18.2
  hooks:
    - id: mypy
      # optional: restrict to same files pattern you want

      files: ^(src/multiple_affiliation_analysis|tests)/
      args:
        - --namespace-packages
        - --explicit-package-bases
        # ensure mypy reads your config file (optional, but explicit)
        - --config-file
        - mypy.ini
      additional_dependencies:
        - pydantic==2.12.0

-   repo: https://github.com/pycqa/isort
    rev: 6.1.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
