name: caa
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - pandas>=2.3.3,<3.0.0
  - geopandas>=1.1.1,<2.0.0
  - scikit-learn>=1.7.2,<2.0.0
  - statsmodels>=0.14.5,<0.15.0
  - matplotlib>=3.10.6,<4.0.0
  - seaborn>=0.13.2,<0.14.0
  - pyarrow>=21.0.0,<22.0.0
  - notebook>=7.5.0,<8.0.0
  - openpyxl>=3.1.5,<4.0.0
  - pip
  - pip:
      - -r requirements.txt
